### ISSUE TITLE
When use startSocket and connectToSocket?

### ISSUE THREAD

**Issue by antoniomldev** [ugo-studio/flutter_p2p_connection#5]
Hello, I understand that the question may seem generic but I'll give an example, I'm new to Flutter and programming in general and that's why I have the question.

Scenario: I am creating an application that will be a Desktop and Mobile application and I want to be able to share information between them, files to be more exact, and I want to allow each person who has the desktop or mobile installed, to be able to share these files as long as be on the same network, therefore,

Should I use startSocket or connectToSocket?

I was unsure, or if I should use both, can you be a little clear on that for me? Thanks! #
/

**Comment by ugo-studio** [comment]
Unfortunately, it's worth noting that the package doesn't support desktop platforms. Now, for your scenario, you would utilize the `startSocket` function to create a host socket, facilitating file sharing among connected devices. Once established, files can be shared to all connected devices, irrespective of whether the sharer is the host or a client. This means that once devices are connected to the host socket, they can all exchange files with each other, fostering a peer-to-peer sharing environment among all connected devices on the same network.

**Comment by antoniomldev** [comment]
Many thanks for the reply.

It became extremely clear what I needed to do.

Unfortunately you said it doesn't have desktop support, are you interested in adding this feature in the future?

If you're not interested in adding it, can you suggest an alternative that could work in both types of applications? Both Mobile and Desktop? WebRTC or conventional Websockets perhaps? It would be interesting if I could also share it on the Desktop as there will be an application installed on the PC.

Thank you again!

**Comment by ugo-studio** [comment]
You're welcome.

I plan on adding desktop support in the future.

But for now, I will recommend you using the conventional websockets.

Make sure the devices are connected to the same wifi. Create a host websocket server in any of the devices, then use `web_socket_channel` package to receive and send data on the client devices.

Example code for creating a host server:
`
void main() async {
  final server = await HttpServer.bind('localhost', 8080);
  print('Server listening on ws://localhost:8080');

  await for (HttpWebSocketRequest request in server) {
    WebSocket webSocket = await request.changeToUpgradeStatus();
    handleWebSocket(webSocket);
  }
}

void handleWebSocket(WebSocket webSocket) {
  webSocket.listen(
    (data) {
      print('Received data: $data');
      webSocket.add('Echo: $data');
    },
    onDone: () => print('WebSocket closed'),
    onError: (error) => print('WebSocket error: $error'),
  );
}
`

**Comment by antoniomldev** [comment]
Cool, I think I understand your code.

Basically I create a localhost and connect the devices to this localhost (as long as they are on the same wifi network) and therefore, via websocket I could pass files between both the mobile and the desktop as long as they are both on the same wifi network connected to this websocket, right?

If so, I understood it and I think I know how to do it.

By the way, could I use the IP of my wifi network as a way to create this port on localhost? Or would it not be necessary?

Thank you again!

**Comment by ugo-studio** [comment]
Yes, You should use the ip of the wifi network

**Comment by antoniomldev** [comment]
Thank you very much for taking the time to help me, sorry for the beginner questions, I really am but thank you for your patience.

I will always keep an eye on your library, any changes, I use it 100%.

Thank you so!

**Comment by Eloks7** [comment]
@ugo-studio I am unable to find any devices with the fetchPeers or streamPeers methods, even when I have created a group with another device. Please is there a step I am missing or something?

**Comment by ugo-studio** [comment]
@Eloks7 you should start streaming peers(`streamPeers()`) then call `discover()` and the discovered peers will be returned in the stream

**Comment by Eloks7** [comment]
@ugo-studio I keep getting "**Error: Peer discovery error - type 'Null' is not a subtype of type 'String'**" error when trying to access the results from stream pairs. Please note I am using Flutterflow.

`bool discoveryStarted = await flutterP2pConnection.discover();
    if (!discoveryStarted) {
      discoveredDevices.add(DeviceStruct(
        deviceName: 'Error: Failed to start peer discovery.',
        deviceAddress: '',
        primaryDeviceType: '',
      ));
      return discoveredDevices;
    }

    // Wait a bit to ensure peers are being discovered
    await Future.delayed(const Duration(seconds: 2));

    // Listen for discovered peers
    _peersSubscription = flutterP2pConnection.streamPeers().listen(
      (peers) {
        discoveredDevices.clear(); // Clear the list to avoid duplicates
        for (var peer in peers) {
          final deviceName = peer.deviceName ?? 'Unknown';
          final deviceAddress = peer.deviceAddress ?? 'Unknown';
          final primaryDeviceType = peer.primaryDeviceType ?? 'Unknown';

          discoveredDevices.add(
            DeviceStruct(
              deviceName: deviceName, // Handle null
              deviceAddress: deviceAddress, // Handle null
              primaryDeviceType: primaryDeviceType, // Handle null
            ),
          );
        }
      },
      onError: (error) {
        discoveredDevices.add(DeviceStruct(
          deviceName: 'Error: Peer discovery error - $error',
          deviceAddress: 'Unknown',
          primaryDeviceType: 'Unknown',
        ));
      },
    );`

**Comment by ugo-studio** [comment]
@Eloks7 According to your code, the error seems to occur here:
dart```
discoveredDevices.add(
        DeviceStruct(
          deviceName: deviceName, // Handle null
          deviceAddress: deviceAddress, // Handle null
          primaryDeviceType: primaryDeviceType, // Handle null
        ),
      );
```

It is a type error. find the value that is null and please let me know.

**Comment by Eloks7** [comment]
` WifiP2PGroupInfo? groupInfo = await flutterP2pConnection.groupInfo();

    // Debugging: Print out the group info
    print('Group Info: $groupInfo');

    if (groupInfo == null) {
      return DeviceStruct(
        deviceName: 'Group info is Null',
        deviceAddress: '-',
      );
    }

    // Access fields directly from the WifiP2PGroupInfo object
    String groupName = groupInfo.groupNetworkName ?? 'Unknown Group';
    String groupRole =
        groupInfo.isGroupOwner == true ? 'Group Owner' : 'Group Member';

    // Combine group info into the DeviceStruct
    return DeviceStruct(
      deviceName: groupName,
      deviceAddress: groupRole,
    );
  } catch (e) {
    // Debugging: Log the error
    print('Error fetching group info: $e');

    // Return error information in DeviceStruct
    return DeviceStruct(
      deviceName: 'Error: ${e.toString()}',
      deviceAddress: '-',
    );`

@ugo-studio I have not been able to find the issue. Same error happens when trying to get "groupInfo", please any other suggestions?

**Comment by Eloks7** [comment]
@ugo-studio According to ChatGPT Deep Research, it says the errors are from the package and not on my end. Please can you look into it.

**Comment by Eloks7** [comment]
@ugo-studio Sorry for the disturbance. These errors don't happen in when I use Local Run but happens in the APK (production environment). Please do you have any ideas what could be causing this?

**Comment by ugo-studio** [comment]
Hi @Eloks7 , 
I need the full exception logs that includes the code line number where the error occurred if possible, it will be helpful to solve the issue

**Comment by Eloks7** [comment]
@ugo-studio Please can I add you to my Flutterflow project so you see my entire implementation? If yes please email me at elokakene@gmail.com with your Flutterflow email address to avoid your email being exposed to the public here.
